### ISSUE TITLE
Error When Running AlphaPanda

### ISSUE THREAD

**Issue by aaaaaaaaa21-code** [YueHuLab/AlphaPanda#1]
Hello,

I’m interested in using the model, but I’m encountering an error when I try to run it. During execution, the data seq heavy seqmap prints information like:

{('B', 1, ' '): 0, ('B', 2, ' '): 1, ('B', 3, ' '): 2, ..., ('B', 16, ' '): 15, ...}

After that, the program fails with the following error:

Sampling:   0%|                                                                                                | 0/100 [00:06<?, ?it/s]
antibody.pdb-H_CDR1:   0%|                                                                                       | 0/2 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "design_AlphaPanda.py", line 4, in <module>
    design_for_pdb(args_from_cmdline())
  File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/tools/runner/design_for_pdb.py", line 233, in design_for_pdb
    traj_batch = model.sample(batch, sample_opt={
  File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/models/diffab.py", line 134, in sample
    traj = self.diffusion.sample(v_0, p_0, s_0, res_feat, pair_feat, mask_generate, mask_res, batch, **sample_opt)
  File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 995, in sample
    v_next, R_next, eps_p, c_denoised = self.eps_net(
  File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 692, in forward
    res_feat2=res_feat.reshape(L, self.res_feat_dim)
RuntimeError: shape '[128, 128]' is invalid for input of size 98304

I would greatly appreciate any assistance in identifying the cause of this RuntimeError and guidance on how to fix it.

Thank you!

**Comment by YueHuLab** [comment]
Thanks for your attention. how about your input file？
 胡岳
***@***.***




---- Replied Message ----
From aaaaaaaaa21-code ***@***.***> Date 09/20/2024 16:31 To YueHuLab/AlphaPanda ***@***.***> Cc Subscribed ***@***.***> Subject [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1)  

Hello,
I’m interested in using the model, but I’m encountering an error when I try to run it. During execution, the data seq heavy seqmap prints information like:
{('B', 1, ' '): 0, ('B', 2, ' '): 1, ('B', 3, ' '): 2, ..., ('B', 16, ' '): 15, ...}
After that, the program fails with the following error:
Sampling: 0%| | 0/100 [00:06<?, ?it/s]
 antibody.pdb-H_CDR1: 0%| | 0/2 [00:06<?, ?it/s]
 Traceback (most recent call last):
 File "design_AlphaPanda.py", line 4, in
 design_for_pdb(args_from_cmdline())
 File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/tools/runner/design_for_pdb.py", line 233, in design_for_pdb
 traj_batch = model.sample(batch, sample_opt={
 File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
 return func(*args, **kwargs)
 File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/models/diffab.py", line 134, in sample
 traj = self.diffusion.sample(v_0, p_0, s_0, res_feat, pair_feat, mask_generate, mask_res, batch, **sample_opt)
 File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
 return func(*args, **kwargs)
 File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 995, in sample
 v_next, R_next, eps_p, c_denoised = self.eps_net(
 File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
 return forward_call(*input, **kwargs)
 File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 692, in forward
 res_feat2=res_feat.reshape(L, self.res_feat_dim)
 RuntimeError: shape '[128, 128]' is invalid for input of size 98304
I would greatly appreciate any assistance in identifying the cause of this RuntimeError and guidance on how to fix it.
Thank you!

**Comment by aaaaaaaaa21-code** [comment]
> Thanks for your attention. how about your input file？ 胡岳 ***@***.***
> […](#)
> ---- Replied Message ---- From aaaaaaaaa21-code ***@***.***> Date 09/20/2024 16:31 To YueHuLab/AlphaPanda ***@***.***> Cc Subscribed ***@***.***> Subject [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1) Hello, I’m interested in using the model, but I’m encountering an error when I try to run it. During execution, the data seq heavy seqmap prints information like: {('B', 1, ' '): 0, ('B', 2, ' '): 1, ('B', 3, ' '): 2, ..., ('B', 16, ' '): 15, ...} After that, the program fails with the following error: Sampling: 0%| | 0/100 [00:06<?, ?it/s] antibody.pdb-H_CDR1: 0%| | 0/2 [00:06<?, ?it/s] Traceback (most recent call last): File "design_AlphaPanda.py", line 4, in design_for_pdb(args_from_cmdline()) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/tools/runner/design_for_pdb.py", line 233, in design_for_pdb traj_batch = model.sample(batch, sample_opt={ File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/models/diffab.py", line 134, in sample traj = self.diffusion.sample(v_0, p_0, s_0, res_feat, pair_feat, mask_generate, mask_res, batch, **sample_opt) File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 995, in sample v_next, R_next, eps_p, c_denoised = self.eps_net( File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 692, in forward res_feat2=res_feat.reshape(L, self.res_feat_dim) RuntimeError: shape '[128, 128]' is invalid for input of size 98304 I would greatly appreciate any assistance in identifying the cause of this RuntimeError and guidance on how to fix it. Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

I input a PDB file of an antigen-antibody complex, where the B chain is the heavy chain of the antibody. I was able to successfully run Diffab with this PDB file.

**Comment by YueHuLab** [comment]
you may design antibody once a time. The software only support design one structure in one run. Have a try. The checkpoint is a toy one. when published, we would make a useful checkpoint public.
 胡岳
***@***.***




---- Replied Message ----
From aaaaaaaaa21-code ***@***.***> Date 09/20/2024 16:46 To YueHuLab/AlphaPanda ***@***.***> Cc Yue Hu ***@***.***>,
Comment ***@***.***> Subject Re: [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1)  

Thanks for your attention. how about your input file？ 胡岳 @.***
 …
 ---- Replied Message ---- From aaaaaaaaa21-code @.> Date 09/20/2024 16:31 To YueHuLab/AlphaPanda @.> Cc Subscribed @.***> Subject [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1) Hello, I’m interested in using the model, but I’m encountering an error when I try to run it. During execution, the data seq heavy seqmap prints information like: {('B', 1, ' '): 0, ('B', 2, ' '): 1, ('B', 3, ' '): 2, ..., ('B', 16, ' '): 15, ...} After that, the program fails with the following error: Sampling: 0%| | 0/100 [00:06<?, ?it/s] antibody.pdb-H_CDR1: 0%| | 0/2 [00:06<?, ?it/s] Traceback (most recent call last): File "design_AlphaPanda.py", line 4, in design_for_pdb(args_from_cmdline()) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/tools/runner/design_for_pdb.py", line 233, in design_for_pdb traj_batch = model.sample(batch, sample_opt={ File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/models/diffab.py", line 134, in sample traj = self.diffusion.sample(v_0, p_0, s_0, res_feat, pair_feat, mask_generate, mask_res, batch, **sample_opt) File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 995, in sample v_next, R_next, eps_p, c_denoised = self.eps_net( File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(input, kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 692, in forward res_feat2=res_feat.reshape(L, self.res_feat_dim) RuntimeError: shape '[128, 128]' is invalid for input of size 98304 I would greatly appreciate any assistance in identifying the cause of this RuntimeError and guidance on how to fix it. Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>
I input a PDB file of an antigen-antibody complex, where the B chain is the heavy chain of the antibody. I was able to successfully run Diffab with this PDB file.

**Comment by YueHuLab** [comment]
Thanks. It not the only antibody pdb,but the complex pdb. Change the *.yml file, to design 1 structure in a run.

 胡岳
***@***.***




---- Replied Message ----
From aaaaaaaaa21-code ***@***.***> Date 09/20/2024 16:58 To YueHuLab/AlphaPanda ***@***.***> Cc Yue Hu ***@***.***>,
Comment ***@***.***> Subject Re: [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1)  

you may design antibody once a time. The software only support design one structure in one run. Have a try. The checkpoint is a toy one. when published, we would make a useful checkpoint public. 胡岳 @.***
 …
 ---- Replied Message ---- From aaaaaaaaa21-code @.> Date 09/20/2024 16:46 To YueHuLab/AlphaPanda @.> Cc Yue Hu @.>, Comment @.> Subject Re: [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1) Thanks for your attention. how about your input file？ 胡岳 @.*** … ---- Replied Message ---- From aaaaaaaaa21-code @.> Date 09/20/2024 16:31 To YueHuLab/AlphaPanda @.> Cc Subscribed @.***> Subject [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1) Hello, I’m interested in using the model, but I’m encountering an error when I try to run it. During execution, the data seq heavy seqmap prints information like: {('B', 1, ' '): 0, ('B', 2, ' '): 1, ('B', 3, ' '): 2, ..., ('B', 16, ' '): 15, ...} After that, the program fails with the following error: Sampling: 0%| | 0/100 [00:06<?, ?it/s] antibody.pdb-H_CDR1: 0%| | 0/2 [00:06<?, ?it/s] Traceback (most recent call last): File "design_AlphaPanda.py", line 4, in design_for_pdb(args_from_cmdline()) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/tools/runner/design_for_pdb.py", line 233, in design_for_pdb traj_batch = model.sample(batch, sample_opt={ File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/models/diffab.py", line 134, in sample traj = self.diffusion.sample(v_0, p_0, s_0, res_feat, pair_feat, mask_generate, mask_res, batch, **sample_opt) File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(args, kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 995, in sample v_next, R_next, eps_p, c_denoised = self.eps_net( File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(input, kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 692, in forward res_feat2=res_feat.reshape(L, self.res_feat_dim) RuntimeError: shape '[128, 128]' is invalid for input of size 98304 I would greatly appreciate any assistance in identifying the cause of this RuntimeError and guidance on how to fix it. Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> I input a PDB file of an antigen-antibody complex, where the B chain is the heavy chain of the antibody. I was able to successfully run Diffab with this PDB file. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>
Thank you for your response. I tried modifying the input to include only the antibody's PDB, but the same error still occurs. I look forward to your new checkpoints.

**Comment by aaaaaaaaa21-code** [comment]
> Thanks. It not the only antibody pdb,but the complex pdb. Change the *.yml file, to design 1 structure in a run. 胡岳 ***@***.***
> […](#)
> ---- Replied Message ---- From aaaaaaaaa21-code ***@***.***> Date 09/20/2024 16:58 To YueHuLab/AlphaPanda ***@***.***> Cc Yue Hu ***@***.***>, Comment ***@***.***> Subject Re: [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1) you may design antibody once a time. The software only support design one structure in one run. Have a try. The checkpoint is a toy one. when published, we would make a useful checkpoint public. 胡岳 @.*** … ---- Replied Message ---- From aaaaaaaaa21-code @.> Date 09/20/2024 16:46 To YueHuLab/AlphaPanda @.> Cc Yue Hu @.>, Comment @.> Subject Re: [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1) Thanks for your attention. how about your input file？ 胡岳 @.*** … ---- Replied Message ---- From aaaaaaaaa21-code @.> Date 09/20/2024 16:31 To YueHuLab/AlphaPanda @.> Cc Subscribed @.***> Subject [YueHuLab/AlphaPanda] Error When Running AlphaPanda (Issue #1) Hello, I’m interested in using the model, but I’m encountering an error when I try to run it. During execution, the data seq heavy seqmap prints information like: {('B', 1, ' '): 0, ('B', 2, ' '): 1, ('B', 3, ' '): 2, ..., ('B', 16, ' '): 15, ...} After that, the program fails with the following error: Sampling: 0%| | 0/100 [00:06<?, ?it/s] antibody.pdb-H_CDR1: 0%| | 0/2 [00:06<?, ?it/s] Traceback (most recent call last): File "design_AlphaPanda.py", line 4, in design_for_pdb(args_from_cmdline()) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/tools/runner/design_for_pdb.py", line 233, in design_for_pdb traj_batch = model.sample(batch, sample_opt={ File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/models/diffab.py", line 134, in sample traj = self.diffusion.sample(v_0, p_0, s_0, res_feat, pair_feat, mask_generate, mask_res, batch, **sample_opt) File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context return func(args, kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 995, in sample v_next, R_next, eps_p, c_denoised = self.eps_net( File "/media/dell/newdisk/mambaforge/envs/AlphaPanda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl return forward_call(input, kwargs) File "/media/dell/newdisk/AlphaPanda-main/AlphaPanda/modules/diffusion/dpm_full.py", line 692, in forward res_feat2=res_feat.reshape(L, self.res_feat_dim) RuntimeError: shape '[128, 128]' is invalid for input of size 98304 I would greatly appreciate any assistance in identifying the cause of this RuntimeError and guidance on how to fix it. Thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.> I input a PDB file of an antigen-antibody complex, where the B chain is the heavy chain of the antibody. I was able to successfully run Diffab with this PDB file. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> Thank you for your response. I tried modifying the input to include only the antibody's PDB, but the same error still occurs. I look forward to your new checkpoints. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Thank you for your help! After changing the design quantity to 1, it successfully ran.
